# Generated by Django 5.1 on 2024-08-28 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_table',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.')]),
        ),
        migrations.AlterField(
            model_name='accounts_table',
            name='security',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='Security question answer must be at least 3 characters long.')]),
        ),
    ]
